notifications:
  irc:
    channels: "chat.freenode.net#firedrake"
    skip_join: true
    on_success: change
    on_failure: always
    template: "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} | %{build_url}"
language: python
# We're not Python 2.6 compatible at the moment
python: "2.7"
env:
  global:
    - C_INCLUDE_PATH=/usr/lib/openmpi/include
    - PETSC_CONFIGURE_OPTIONS="--with-fortran-interfaces=1 --with-c++-support"
  matrix:
    - PYOP2_BACKEND=sequential
    - OMP_NUM_THREADS=1 PYOP2_BACKEND=openmp
    - OMP_NUM_THREADS=2 PYOP2_BACKEND=openmp
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:amcg/backports
  - sudo apt-get update
  - "sudo apt-get install -qq build-essential python-dev git-core mercurial \
    cmake cmake-curses-gui gmsh python-gmsh python-pip swig libhdf5-openmpi-dev \
    libopenmpi-dev openmpi-bin libblas-dev liblapack-dev gfortran triangle-bin \
    libvtk5-dev python-vtk libparmetis-dev python-vtk"
  - wget https://github.com/OP2/PyOP2/raw/master/requirements-minimal.txt
  - pip install "petsc>=3.4" -r requirements-minimal.txt --use-mirrors
  - pip install git+https://github.com/OP2/PyOP2 cgen
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install argparse ordereddict; fi
install:
  - ./configure
  - make python_build
# command to run tests
script:
  - export PYTHONPATH=`pwd`/python:$PYTHONPATH
  - flake8
  - py.test -n 2 -v tests
